// 文字コード：UTF-8
#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout (local_size_x = 16, local_size_y = 16) in;

layout(std430, set = 0, binding = 0) buffer OutputDataType{
    uint elems[];
} outputData;

void main()
{
   uint width = 16 * 4;
	uint idx = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * width;
   outputData.elems[idx] = idx * 2;
}

// EOF
